version: '2.1'

services:
  login:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: login
    container_name: login
    ports:
      - '8096:8096'
  redis:
    image: 'redis:latest'